# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jb/Documents/Repos/voraldo/Voraldo-v1.2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jb/Documents/Repos/voraldo/Voraldo-v1.2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jb/Documents/Repos/voraldo/Voraldo-v1.2/CMakeFiles /home/jb/Documents/Repos/voraldo/Voraldo-v1.2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jb/Documents/Repos/voraldo/Voraldo-v1.2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named exe

# Build rule for target.
exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exe
.PHONY : exe

# fast build rule for target.
exe/fast:
	$(MAKE) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/build
.PHONY : exe/fast

#=============================================================================
# Target rules for targets named BigInt

# Build rule for target.
BigInt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BigInt
.PHONY : BigInt

# fast build rule for target.
BigInt/fast:
	$(MAKE) -f CMakeFiles/BigInt.dir/build.make CMakeFiles/BigInt.dir/build
.PHONY : BigInt/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named FastNoise

# Build rule for target.
FastNoise: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FastNoise
.PHONY : FastNoise

# fast build rule for target.
FastNoise/fast:
	$(MAKE) -f resources/FastNoise2/src/CMakeFiles/FastNoise.dir/build.make resources/FastNoise2/src/CMakeFiles/FastNoise.dir/build
.PHONY : FastNoise/fast

#=============================================================================
# Target rules for targets named NoiseTool

# Build rule for target.
NoiseTool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NoiseTool
.PHONY : NoiseTool

# fast build rule for target.
NoiseTool/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/CMakeFiles/NoiseTool.dir/build.make resources/FastNoise2/NoiseTool/CMakeFiles/NoiseTool.dir/build
.PHONY : NoiseTool/fast

#=============================================================================
# Target rules for targets named Corrade

# Build rule for target.
Corrade: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Corrade
.PHONY : Corrade

# fast build rule for target.
Corrade/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/corrade/src/Corrade/CMakeFiles/Corrade.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/corrade/src/Corrade/CMakeFiles/Corrade.dir/build
.PHONY : Corrade/fast

#=============================================================================
# Target rules for targets named CorradeContainers-headers

# Build rule for target.
CorradeContainers-headers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CorradeContainers-headers
.PHONY : CorradeContainers-headers

# fast build rule for target.
CorradeContainers-headers/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/corrade/src/Corrade/Containers/CMakeFiles/CorradeContainers-headers.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/corrade/src/Corrade/Containers/CMakeFiles/CorradeContainers-headers.dir/build
.PHONY : CorradeContainers-headers/fast

#=============================================================================
# Target rules for targets named CorradeInterconnect

# Build rule for target.
CorradeInterconnect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CorradeInterconnect
.PHONY : CorradeInterconnect

# fast build rule for target.
CorradeInterconnect/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/corrade/src/Corrade/Interconnect/CMakeFiles/CorradeInterconnect.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/corrade/src/Corrade/Interconnect/CMakeFiles/CorradeInterconnect.dir/build
.PHONY : CorradeInterconnect/fast

#=============================================================================
# Target rules for targets named CorradePluginManager

# Build rule for target.
CorradePluginManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CorradePluginManager
.PHONY : CorradePluginManager

# fast build rule for target.
CorradePluginManager/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/corrade/src/Corrade/PluginManager/CMakeFiles/CorradePluginManager.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/corrade/src/Corrade/PluginManager/CMakeFiles/CorradePluginManager.dir/build
.PHONY : CorradePluginManager/fast

#=============================================================================
# Target rules for targets named CorradePluginManagerObjects

# Build rule for target.
CorradePluginManagerObjects: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CorradePluginManagerObjects
.PHONY : CorradePluginManagerObjects

# fast build rule for target.
CorradePluginManagerObjects/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/corrade/src/Corrade/PluginManager/CMakeFiles/CorradePluginManagerObjects.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/corrade/src/Corrade/PluginManager/CMakeFiles/CorradePluginManagerObjects.dir/build
.PHONY : CorradePluginManagerObjects/fast

#=============================================================================
# Target rules for targets named corrade-rc

# Build rule for target.
corrade-rc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 corrade-rc
.PHONY : corrade-rc

# fast build rule for target.
corrade-rc/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/corrade/src/Corrade/Utility/CMakeFiles/corrade-rc.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/corrade/src/Corrade/Utility/CMakeFiles/corrade-rc.dir/build
.PHONY : corrade-rc/fast

#=============================================================================
# Target rules for targets named CorradeUtility

# Build rule for target.
CorradeUtility: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CorradeUtility
.PHONY : CorradeUtility

# fast build rule for target.
CorradeUtility/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/corrade/src/Corrade/Utility/CMakeFiles/CorradeUtility.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/corrade/src/Corrade/Utility/CMakeFiles/CorradeUtility.dir/build
.PHONY : CorradeUtility/fast

#=============================================================================
# Target rules for targets named CorradeUtilityObjects

# Build rule for target.
CorradeUtilityObjects: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CorradeUtilityObjects
.PHONY : CorradeUtilityObjects

# fast build rule for target.
CorradeUtilityObjects/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/corrade/src/Corrade/Utility/CMakeFiles/CorradeUtilityObjects.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/corrade/src/Corrade/Utility/CMakeFiles/CorradeUtilityObjects.dir/build
.PHONY : CorradeUtilityObjects/fast

#=============================================================================
# Target rules for targets named MagnumFlextGLObjects

# Build rule for target.
MagnumFlextGLObjects: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumFlextGLObjects
.PHONY : MagnumFlextGLObjects

# fast build rule for target.
MagnumFlextGLObjects/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/MagnumExternal/OpenGL/GL/CMakeFiles/MagnumFlextGLObjects.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/MagnumExternal/OpenGL/GL/CMakeFiles/MagnumFlextGLObjects.dir/build
.PHONY : MagnumFlextGLObjects/fast

#=============================================================================
# Target rules for targets named Magnum

# Build rule for target.
Magnum: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Magnum
.PHONY : Magnum

# fast build rule for target.
Magnum/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/CMakeFiles/Magnum.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/CMakeFiles/Magnum.dir/build
.PHONY : Magnum/fast

#=============================================================================
# Target rules for targets named MagnumObjects

# Build rule for target.
MagnumObjects: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumObjects
.PHONY : MagnumObjects

# fast build rule for target.
MagnumObjects/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/CMakeFiles/MagnumObjects.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/CMakeFiles/MagnumObjects.dir/build
.PHONY : MagnumObjects/fast

#=============================================================================
# Target rules for targets named MagnumMathObjects

# Build rule for target.
MagnumMathObjects: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumMathObjects
.PHONY : MagnumMathObjects

# fast build rule for target.
MagnumMathObjects/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/CMakeFiles/MagnumMathObjects.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/CMakeFiles/MagnumMathObjects.dir/build
.PHONY : MagnumMathObjects/fast

#=============================================================================
# Target rules for targets named MagnumAnimation

# Build rule for target.
MagnumAnimation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumAnimation
.PHONY : MagnumAnimation

# fast build rule for target.
MagnumAnimation/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Animation/CMakeFiles/MagnumAnimation.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Animation/CMakeFiles/MagnumAnimation.dir/build
.PHONY : MagnumAnimation/fast

#=============================================================================
# Target rules for targets named MagnumMath

# Build rule for target.
MagnumMath: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumMath
.PHONY : MagnumMath

# fast build rule for target.
MagnumMath/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Math/CMakeFiles/MagnumMath.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Math/CMakeFiles/MagnumMath.dir/build
.PHONY : MagnumMath/fast

#=============================================================================
# Target rules for targets named MagnumMathAlgorithms

# Build rule for target.
MagnumMathAlgorithms: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumMathAlgorithms
.PHONY : MagnumMathAlgorithms

# fast build rule for target.
MagnumMathAlgorithms/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Math/Algorithms/CMakeFiles/MagnumMathAlgorithms.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Math/Algorithms/CMakeFiles/MagnumMathAlgorithms.dir/build
.PHONY : MagnumMathAlgorithms/fast

#=============================================================================
# Target rules for targets named MagnumPlatform

# Build rule for target.
MagnumPlatform: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumPlatform
.PHONY : MagnumPlatform

# fast build rule for target.
MagnumPlatform/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Platform/CMakeFiles/MagnumPlatform.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Platform/CMakeFiles/MagnumPlatform.dir/build
.PHONY : MagnumPlatform/fast

#=============================================================================
# Target rules for targets named MagnumGlxContextObjects

# Build rule for target.
MagnumGlxContextObjects: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumGlxContextObjects
.PHONY : MagnumGlxContextObjects

# fast build rule for target.
MagnumGlxContextObjects/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Platform/CMakeFiles/MagnumGlxContextObjects.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Platform/CMakeFiles/MagnumGlxContextObjects.dir/build
.PHONY : MagnumGlxContextObjects/fast

#=============================================================================
# Target rules for targets named MagnumSdl2Application

# Build rule for target.
MagnumSdl2Application: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumSdl2Application
.PHONY : MagnumSdl2Application

# fast build rule for target.
MagnumSdl2Application/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Platform/CMakeFiles/MagnumSdl2Application.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Platform/CMakeFiles/MagnumSdl2Application.dir/build
.PHONY : MagnumSdl2Application/fast

#=============================================================================
# Target rules for targets named MagnumPlatformObjects

# Build rule for target.
MagnumPlatformObjects: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumPlatformObjects
.PHONY : MagnumPlatformObjects

# fast build rule for target.
MagnumPlatformObjects/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Platform/CMakeFiles/MagnumPlatformObjects.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Platform/CMakeFiles/MagnumPlatformObjects.dir/build
.PHONY : MagnumPlatformObjects/fast

#=============================================================================
# Target rules for targets named MagnumDebugTools

# Build rule for target.
MagnumDebugTools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumDebugTools
.PHONY : MagnumDebugTools

# fast build rule for target.
MagnumDebugTools/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/DebugTools/CMakeFiles/MagnumDebugTools.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/DebugTools/CMakeFiles/MagnumDebugTools.dir/build
.PHONY : MagnumDebugTools/fast

#=============================================================================
# Target rules for targets named MagnumDebugToolsObjects

# Build rule for target.
MagnumDebugToolsObjects: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumDebugToolsObjects
.PHONY : MagnumDebugToolsObjects

# fast build rule for target.
MagnumDebugToolsObjects/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/DebugTools/CMakeFiles/MagnumDebugToolsObjects.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/DebugTools/CMakeFiles/MagnumDebugToolsObjects.dir/build
.PHONY : MagnumDebugToolsObjects/fast

#=============================================================================
# Target rules for targets named MagnumGL

# Build rule for target.
MagnumGL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumGL
.PHONY : MagnumGL

# fast build rule for target.
MagnumGL/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/GL/CMakeFiles/MagnumGL.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/GL/CMakeFiles/MagnumGL.dir/build
.PHONY : MagnumGL/fast

#=============================================================================
# Target rules for targets named MagnumGLObjects

# Build rule for target.
MagnumGLObjects: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumGLObjects
.PHONY : MagnumGLObjects

# fast build rule for target.
MagnumGLObjects/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/GL/CMakeFiles/MagnumGLObjects.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/GL/CMakeFiles/MagnumGLObjects.dir/build
.PHONY : MagnumGLObjects/fast

#=============================================================================
# Target rules for targets named MagnumPrimitives

# Build rule for target.
MagnumPrimitives: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumPrimitives
.PHONY : MagnumPrimitives

# fast build rule for target.
MagnumPrimitives/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Primitives/CMakeFiles/MagnumPrimitives.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Primitives/CMakeFiles/MagnumPrimitives.dir/build
.PHONY : MagnumPrimitives/fast

#=============================================================================
# Target rules for targets named MagnumSceneGraph

# Build rule for target.
MagnumSceneGraph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumSceneGraph
.PHONY : MagnumSceneGraph

# fast build rule for target.
MagnumSceneGraph/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/SceneGraph/CMakeFiles/MagnumSceneGraph.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/SceneGraph/CMakeFiles/MagnumSceneGraph.dir/build
.PHONY : MagnumSceneGraph/fast

#=============================================================================
# Target rules for targets named MagnumSceneGraphObjects

# Build rule for target.
MagnumSceneGraphObjects: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumSceneGraphObjects
.PHONY : MagnumSceneGraphObjects

# fast build rule for target.
MagnumSceneGraphObjects/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/SceneGraph/CMakeFiles/MagnumSceneGraphObjects.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/SceneGraph/CMakeFiles/MagnumSceneGraphObjects.dir/build
.PHONY : MagnumSceneGraphObjects/fast

#=============================================================================
# Target rules for targets named MagnumShaders

# Build rule for target.
MagnumShaders: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumShaders
.PHONY : MagnumShaders

# fast build rule for target.
MagnumShaders/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Shaders/CMakeFiles/MagnumShaders.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Shaders/CMakeFiles/MagnumShaders.dir/build
.PHONY : MagnumShaders/fast

#=============================================================================
# Target rules for targets named MagnumShadersObjects

# Build rule for target.
MagnumShadersObjects: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumShadersObjects
.PHONY : MagnumShadersObjects

# fast build rule for target.
MagnumShadersObjects/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Shaders/CMakeFiles/MagnumShadersObjects.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Shaders/CMakeFiles/MagnumShadersObjects.dir/build
.PHONY : MagnumShadersObjects/fast

#=============================================================================
# Target rules for targets named MagnumShaders_RCS-dependencies

# Build rule for target.
MagnumShaders_RCS-dependencies: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumShaders_RCS-dependencies
.PHONY : MagnumShaders_RCS-dependencies

# fast build rule for target.
MagnumShaders_RCS-dependencies/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Shaders/CMakeFiles/MagnumShaders_RCS-dependencies.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Shaders/CMakeFiles/MagnumShaders_RCS-dependencies.dir/build
.PHONY : MagnumShaders_RCS-dependencies/fast

#=============================================================================
# Target rules for targets named MagnumShaderTools

# Build rule for target.
MagnumShaderTools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumShaderTools
.PHONY : MagnumShaderTools

# fast build rule for target.
MagnumShaderTools/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/ShaderTools/CMakeFiles/MagnumShaderTools.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/ShaderTools/CMakeFiles/MagnumShaderTools.dir/build
.PHONY : MagnumShaderTools/fast

#=============================================================================
# Target rules for targets named MagnumTrade

# Build rule for target.
MagnumTrade: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumTrade
.PHONY : MagnumTrade

# fast build rule for target.
MagnumTrade/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Trade/CMakeFiles/MagnumTrade.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Trade/CMakeFiles/MagnumTrade.dir/build
.PHONY : MagnumTrade/fast

#=============================================================================
# Target rules for targets named MagnumTradeObjects

# Build rule for target.
MagnumTradeObjects: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumTradeObjects
.PHONY : MagnumTradeObjects

# fast build rule for target.
MagnumTradeObjects/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Trade/CMakeFiles/MagnumTradeObjects.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum/src/Magnum/Trade/CMakeFiles/MagnumTradeObjects.dir/build
.PHONY : MagnumTradeObjects/fast

#=============================================================================
# Target rules for targets named MagnumImGuiIntegration

# Build rule for target.
MagnumImGuiIntegration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MagnumImGuiIntegration
.PHONY : MagnumImGuiIntegration

# fast build rule for target.
MagnumImGuiIntegration/fast:
	$(MAKE) -f resources/FastNoise2/NoiseTool/ThirdParty/magnum-integration/src/Magnum/ImGuiIntegration/CMakeFiles/MagnumImGuiIntegration.dir/build.make resources/FastNoise2/NoiseTool/ThirdParty/magnum-integration/src/Magnum/ImGuiIntegration/CMakeFiles/MagnumImGuiIntegration.dir/build
.PHONY : MagnumImGuiIntegration/fast

resources/VAT/mmccutchen_BigInt/BigInteger.o: resources/VAT/mmccutchen_BigInt/BigInteger.cc.o

.PHONY : resources/VAT/mmccutchen_BigInt/BigInteger.o

# target to build an object file
resources/VAT/mmccutchen_BigInt/BigInteger.cc.o:
	$(MAKE) -f CMakeFiles/BigInt.dir/build.make CMakeFiles/BigInt.dir/resources/VAT/mmccutchen_BigInt/BigInteger.cc.o
.PHONY : resources/VAT/mmccutchen_BigInt/BigInteger.cc.o

resources/VAT/mmccutchen_BigInt/BigInteger.i: resources/VAT/mmccutchen_BigInt/BigInteger.cc.i

.PHONY : resources/VAT/mmccutchen_BigInt/BigInteger.i

# target to preprocess a source file
resources/VAT/mmccutchen_BigInt/BigInteger.cc.i:
	$(MAKE) -f CMakeFiles/BigInt.dir/build.make CMakeFiles/BigInt.dir/resources/VAT/mmccutchen_BigInt/BigInteger.cc.i
.PHONY : resources/VAT/mmccutchen_BigInt/BigInteger.cc.i

resources/VAT/mmccutchen_BigInt/BigInteger.s: resources/VAT/mmccutchen_BigInt/BigInteger.cc.s

.PHONY : resources/VAT/mmccutchen_BigInt/BigInteger.s

# target to generate assembly for a file
resources/VAT/mmccutchen_BigInt/BigInteger.cc.s:
	$(MAKE) -f CMakeFiles/BigInt.dir/build.make CMakeFiles/BigInt.dir/resources/VAT/mmccutchen_BigInt/BigInteger.cc.s
.PHONY : resources/VAT/mmccutchen_BigInt/BigInteger.cc.s

resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.o: resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.cc.o

.PHONY : resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.o

# target to build an object file
resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.cc.o:
	$(MAKE) -f CMakeFiles/BigInt.dir/build.make CMakeFiles/BigInt.dir/resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.cc.o
.PHONY : resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.cc.o

resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.i: resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.cc.i

.PHONY : resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.i

# target to preprocess a source file
resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.cc.i:
	$(MAKE) -f CMakeFiles/BigInt.dir/build.make CMakeFiles/BigInt.dir/resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.cc.i
.PHONY : resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.cc.i

resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.s: resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.cc.s

.PHONY : resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.s

# target to generate assembly for a file
resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.cc.s:
	$(MAKE) -f CMakeFiles/BigInt.dir/build.make CMakeFiles/BigInt.dir/resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.cc.s
.PHONY : resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.cc.s

resources/VAT/mmccutchen_BigInt/BigIntegerUtils.o: resources/VAT/mmccutchen_BigInt/BigIntegerUtils.cc.o

.PHONY : resources/VAT/mmccutchen_BigInt/BigIntegerUtils.o

# target to build an object file
resources/VAT/mmccutchen_BigInt/BigIntegerUtils.cc.o:
	$(MAKE) -f CMakeFiles/BigInt.dir/build.make CMakeFiles/BigInt.dir/resources/VAT/mmccutchen_BigInt/BigIntegerUtils.cc.o
.PHONY : resources/VAT/mmccutchen_BigInt/BigIntegerUtils.cc.o

resources/VAT/mmccutchen_BigInt/BigIntegerUtils.i: resources/VAT/mmccutchen_BigInt/BigIntegerUtils.cc.i

.PHONY : resources/VAT/mmccutchen_BigInt/BigIntegerUtils.i

# target to preprocess a source file
resources/VAT/mmccutchen_BigInt/BigIntegerUtils.cc.i:
	$(MAKE) -f CMakeFiles/BigInt.dir/build.make CMakeFiles/BigInt.dir/resources/VAT/mmccutchen_BigInt/BigIntegerUtils.cc.i
.PHONY : resources/VAT/mmccutchen_BigInt/BigIntegerUtils.cc.i

resources/VAT/mmccutchen_BigInt/BigIntegerUtils.s: resources/VAT/mmccutchen_BigInt/BigIntegerUtils.cc.s

.PHONY : resources/VAT/mmccutchen_BigInt/BigIntegerUtils.s

# target to generate assembly for a file
resources/VAT/mmccutchen_BigInt/BigIntegerUtils.cc.s:
	$(MAKE) -f CMakeFiles/BigInt.dir/build.make CMakeFiles/BigInt.dir/resources/VAT/mmccutchen_BigInt/BigIntegerUtils.cc.s
.PHONY : resources/VAT/mmccutchen_BigInt/BigIntegerUtils.cc.s

resources/VAT/mmccutchen_BigInt/BigUnsigned.o: resources/VAT/mmccutchen_BigInt/BigUnsigned.cc.o

.PHONY : resources/VAT/mmccutchen_BigInt/BigUnsigned.o

# target to build an object file
resources/VAT/mmccutchen_BigInt/BigUnsigned.cc.o:
	$(MAKE) -f CMakeFiles/BigInt.dir/build.make CMakeFiles/BigInt.dir/resources/VAT/mmccutchen_BigInt/BigUnsigned.cc.o
.PHONY : resources/VAT/mmccutchen_BigInt/BigUnsigned.cc.o

resources/VAT/mmccutchen_BigInt/BigUnsigned.i: resources/VAT/mmccutchen_BigInt/BigUnsigned.cc.i

.PHONY : resources/VAT/mmccutchen_BigInt/BigUnsigned.i

# target to preprocess a source file
resources/VAT/mmccutchen_BigInt/BigUnsigned.cc.i:
	$(MAKE) -f CMakeFiles/BigInt.dir/build.make CMakeFiles/BigInt.dir/resources/VAT/mmccutchen_BigInt/BigUnsigned.cc.i
.PHONY : resources/VAT/mmccutchen_BigInt/BigUnsigned.cc.i

resources/VAT/mmccutchen_BigInt/BigUnsigned.s: resources/VAT/mmccutchen_BigInt/BigUnsigned.cc.s

.PHONY : resources/VAT/mmccutchen_BigInt/BigUnsigned.s

# target to generate assembly for a file
resources/VAT/mmccutchen_BigInt/BigUnsigned.cc.s:
	$(MAKE) -f CMakeFiles/BigInt.dir/build.make CMakeFiles/BigInt.dir/resources/VAT/mmccutchen_BigInt/BigUnsigned.cc.s
.PHONY : resources/VAT/mmccutchen_BigInt/BigUnsigned.cc.s

resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.o: resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.cc.o

.PHONY : resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.o

# target to build an object file
resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.cc.o:
	$(MAKE) -f CMakeFiles/BigInt.dir/build.make CMakeFiles/BigInt.dir/resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.cc.o
.PHONY : resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.cc.o

resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.i: resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.cc.i

.PHONY : resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.i

# target to preprocess a source file
resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.cc.i:
	$(MAKE) -f CMakeFiles/BigInt.dir/build.make CMakeFiles/BigInt.dir/resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.cc.i
.PHONY : resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.cc.i

resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.s: resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.cc.s

.PHONY : resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.s

# target to generate assembly for a file
resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.cc.s:
	$(MAKE) -f CMakeFiles/BigInt.dir/build.make CMakeFiles/BigInt.dir/resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.cc.s
.PHONY : resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.cc.s

resources/engine_code/engine.o: resources/engine_code/engine.cc.o

.PHONY : resources/engine_code/engine.o

# target to build an object file
resources/engine_code/engine.cc.o:
	$(MAKE) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/resources/engine_code/engine.cc.o
.PHONY : resources/engine_code/engine.cc.o

resources/engine_code/engine.i: resources/engine_code/engine.cc.i

.PHONY : resources/engine_code/engine.i

# target to preprocess a source file
resources/engine_code/engine.cc.i:
	$(MAKE) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/resources/engine_code/engine.cc.i
.PHONY : resources/engine_code/engine.cc.i

resources/engine_code/engine.s: resources/engine_code/engine.cc.s

.PHONY : resources/engine_code/engine.s

# target to generate assembly for a file
resources/engine_code/engine.cc.s:
	$(MAKE) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/resources/engine_code/engine.cc.s
.PHONY : resources/engine_code/engine.cc.s

resources/engine_code/engine_utils.o: resources/engine_code/engine_utils.cc.o

.PHONY : resources/engine_code/engine_utils.o

# target to build an object file
resources/engine_code/engine_utils.cc.o:
	$(MAKE) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/resources/engine_code/engine_utils.cc.o
.PHONY : resources/engine_code/engine_utils.cc.o

resources/engine_code/engine_utils.i: resources/engine_code/engine_utils.cc.i

.PHONY : resources/engine_code/engine_utils.i

# target to preprocess a source file
resources/engine_code/engine_utils.cc.i:
	$(MAKE) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/resources/engine_code/engine_utils.cc.i
.PHONY : resources/engine_code/engine_utils.cc.i

resources/engine_code/engine_utils.s: resources/engine_code/engine_utils.cc.s

.PHONY : resources/engine_code/engine_utils.s

# target to generate assembly for a file
resources/engine_code/engine_utils.cc.s:
	$(MAKE) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/resources/engine_code/engine_utils.cc.s
.PHONY : resources/engine_code/engine_utils.cc.s

resources/engine_code/gpu_data.o: resources/engine_code/gpu_data.cc.o

.PHONY : resources/engine_code/gpu_data.o

# target to build an object file
resources/engine_code/gpu_data.cc.o:
	$(MAKE) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/resources/engine_code/gpu_data.cc.o
.PHONY : resources/engine_code/gpu_data.cc.o

resources/engine_code/gpu_data.i: resources/engine_code/gpu_data.cc.i

.PHONY : resources/engine_code/gpu_data.i

# target to preprocess a source file
resources/engine_code/gpu_data.cc.i:
	$(MAKE) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/resources/engine_code/gpu_data.cc.i
.PHONY : resources/engine_code/gpu_data.cc.i

resources/engine_code/gpu_data.s: resources/engine_code/gpu_data.cc.s

.PHONY : resources/engine_code/gpu_data.s

# target to generate assembly for a file
resources/engine_code/gpu_data.cc.s:
	$(MAKE) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/resources/engine_code/gpu_data.cc.s
.PHONY : resources/engine_code/gpu_data.cc.s

resources/engine_code/main.o: resources/engine_code/main.cc.o

.PHONY : resources/engine_code/main.o

# target to build an object file
resources/engine_code/main.cc.o:
	$(MAKE) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/resources/engine_code/main.cc.o
.PHONY : resources/engine_code/main.cc.o

resources/engine_code/main.i: resources/engine_code/main.cc.i

.PHONY : resources/engine_code/main.i

# target to preprocess a source file
resources/engine_code/main.cc.i:
	$(MAKE) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/resources/engine_code/main.cc.i
.PHONY : resources/engine_code/main.cc.i

resources/engine_code/main.s: resources/engine_code/main.cc.s

.PHONY : resources/engine_code/main.s

# target to generate assembly for a file
resources/engine_code/main.cc.s:
	$(MAKE) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/resources/engine_code/main.cc.s
.PHONY : resources/engine_code/main.cc.s

resources/lodev_lodePNG/lodepng.o: resources/lodev_lodePNG/lodepng.cc.o

.PHONY : resources/lodev_lodePNG/lodepng.o

# target to build an object file
resources/lodev_lodePNG/lodepng.cc.o:
	$(MAKE) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/resources/lodev_lodePNG/lodepng.cc.o
.PHONY : resources/lodev_lodePNG/lodepng.cc.o

resources/lodev_lodePNG/lodepng.i: resources/lodev_lodePNG/lodepng.cc.i

.PHONY : resources/lodev_lodePNG/lodepng.i

# target to preprocess a source file
resources/lodev_lodePNG/lodepng.cc.i:
	$(MAKE) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/resources/lodev_lodePNG/lodepng.cc.i
.PHONY : resources/lodev_lodePNG/lodepng.cc.i

resources/lodev_lodePNG/lodepng.s: resources/lodev_lodePNG/lodepng.cc.s

.PHONY : resources/lodev_lodePNG/lodepng.s

# target to generate assembly for a file
resources/lodev_lodePNG/lodepng.cc.s:
	$(MAKE) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/resources/lodev_lodePNG/lodepng.cc.s
.PHONY : resources/lodev_lodePNG/lodepng.cc.s

resources/ocornut_imgui/TextEditor.o: resources/ocornut_imgui/TextEditor.cpp.o

.PHONY : resources/ocornut_imgui/TextEditor.o

# target to build an object file
resources/ocornut_imgui/TextEditor.cpp.o:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/TextEditor.cpp.o
.PHONY : resources/ocornut_imgui/TextEditor.cpp.o

resources/ocornut_imgui/TextEditor.i: resources/ocornut_imgui/TextEditor.cpp.i

.PHONY : resources/ocornut_imgui/TextEditor.i

# target to preprocess a source file
resources/ocornut_imgui/TextEditor.cpp.i:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/TextEditor.cpp.i
.PHONY : resources/ocornut_imgui/TextEditor.cpp.i

resources/ocornut_imgui/TextEditor.s: resources/ocornut_imgui/TextEditor.cpp.s

.PHONY : resources/ocornut_imgui/TextEditor.s

# target to generate assembly for a file
resources/ocornut_imgui/TextEditor.cpp.s:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/TextEditor.cpp.s
.PHONY : resources/ocornut_imgui/TextEditor.cpp.s

resources/ocornut_imgui/imgui.o: resources/ocornut_imgui/imgui.cc.o

.PHONY : resources/ocornut_imgui/imgui.o

# target to build an object file
resources/ocornut_imgui/imgui.cc.o:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui.cc.o
.PHONY : resources/ocornut_imgui/imgui.cc.o

resources/ocornut_imgui/imgui.i: resources/ocornut_imgui/imgui.cc.i

.PHONY : resources/ocornut_imgui/imgui.i

# target to preprocess a source file
resources/ocornut_imgui/imgui.cc.i:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui.cc.i
.PHONY : resources/ocornut_imgui/imgui.cc.i

resources/ocornut_imgui/imgui.s: resources/ocornut_imgui/imgui.cc.s

.PHONY : resources/ocornut_imgui/imgui.s

# target to generate assembly for a file
resources/ocornut_imgui/imgui.cc.s:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui.cc.s
.PHONY : resources/ocornut_imgui/imgui.cc.s

resources/ocornut_imgui/imgui_demo.o: resources/ocornut_imgui/imgui_demo.cc.o

.PHONY : resources/ocornut_imgui/imgui_demo.o

# target to build an object file
resources/ocornut_imgui/imgui_demo.cc.o:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_demo.cc.o
.PHONY : resources/ocornut_imgui/imgui_demo.cc.o

resources/ocornut_imgui/imgui_demo.i: resources/ocornut_imgui/imgui_demo.cc.i

.PHONY : resources/ocornut_imgui/imgui_demo.i

# target to preprocess a source file
resources/ocornut_imgui/imgui_demo.cc.i:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_demo.cc.i
.PHONY : resources/ocornut_imgui/imgui_demo.cc.i

resources/ocornut_imgui/imgui_demo.s: resources/ocornut_imgui/imgui_demo.cc.s

.PHONY : resources/ocornut_imgui/imgui_demo.s

# target to generate assembly for a file
resources/ocornut_imgui/imgui_demo.cc.s:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_demo.cc.s
.PHONY : resources/ocornut_imgui/imgui_demo.cc.s

resources/ocornut_imgui/imgui_draw.o: resources/ocornut_imgui/imgui_draw.cc.o

.PHONY : resources/ocornut_imgui/imgui_draw.o

# target to build an object file
resources/ocornut_imgui/imgui_draw.cc.o:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_draw.cc.o
.PHONY : resources/ocornut_imgui/imgui_draw.cc.o

resources/ocornut_imgui/imgui_draw.i: resources/ocornut_imgui/imgui_draw.cc.i

.PHONY : resources/ocornut_imgui/imgui_draw.i

# target to preprocess a source file
resources/ocornut_imgui/imgui_draw.cc.i:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_draw.cc.i
.PHONY : resources/ocornut_imgui/imgui_draw.cc.i

resources/ocornut_imgui/imgui_draw.s: resources/ocornut_imgui/imgui_draw.cc.s

.PHONY : resources/ocornut_imgui/imgui_draw.s

# target to generate assembly for a file
resources/ocornut_imgui/imgui_draw.cc.s:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_draw.cc.s
.PHONY : resources/ocornut_imgui/imgui_draw.cc.s

resources/ocornut_imgui/imgui_gl3w.o: resources/ocornut_imgui/imgui_gl3w.c.o

.PHONY : resources/ocornut_imgui/imgui_gl3w.o

# target to build an object file
resources/ocornut_imgui/imgui_gl3w.c.o:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_gl3w.c.o
.PHONY : resources/ocornut_imgui/imgui_gl3w.c.o

resources/ocornut_imgui/imgui_gl3w.i: resources/ocornut_imgui/imgui_gl3w.c.i

.PHONY : resources/ocornut_imgui/imgui_gl3w.i

# target to preprocess a source file
resources/ocornut_imgui/imgui_gl3w.c.i:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_gl3w.c.i
.PHONY : resources/ocornut_imgui/imgui_gl3w.c.i

resources/ocornut_imgui/imgui_gl3w.s: resources/ocornut_imgui/imgui_gl3w.c.s

.PHONY : resources/ocornut_imgui/imgui_gl3w.s

# target to generate assembly for a file
resources/ocornut_imgui/imgui_gl3w.c.s:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_gl3w.c.s
.PHONY : resources/ocornut_imgui/imgui_gl3w.c.s

resources/ocornut_imgui/imgui_impl_opengl3.o: resources/ocornut_imgui/imgui_impl_opengl3.cc.o

.PHONY : resources/ocornut_imgui/imgui_impl_opengl3.o

# target to build an object file
resources/ocornut_imgui/imgui_impl_opengl3.cc.o:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_impl_opengl3.cc.o
.PHONY : resources/ocornut_imgui/imgui_impl_opengl3.cc.o

resources/ocornut_imgui/imgui_impl_opengl3.i: resources/ocornut_imgui/imgui_impl_opengl3.cc.i

.PHONY : resources/ocornut_imgui/imgui_impl_opengl3.i

# target to preprocess a source file
resources/ocornut_imgui/imgui_impl_opengl3.cc.i:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_impl_opengl3.cc.i
.PHONY : resources/ocornut_imgui/imgui_impl_opengl3.cc.i

resources/ocornut_imgui/imgui_impl_opengl3.s: resources/ocornut_imgui/imgui_impl_opengl3.cc.s

.PHONY : resources/ocornut_imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
resources/ocornut_imgui/imgui_impl_opengl3.cc.s:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_impl_opengl3.cc.s
.PHONY : resources/ocornut_imgui/imgui_impl_opengl3.cc.s

resources/ocornut_imgui/imgui_impl_sdl.o: resources/ocornut_imgui/imgui_impl_sdl.cc.o

.PHONY : resources/ocornut_imgui/imgui_impl_sdl.o

# target to build an object file
resources/ocornut_imgui/imgui_impl_sdl.cc.o:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_impl_sdl.cc.o
.PHONY : resources/ocornut_imgui/imgui_impl_sdl.cc.o

resources/ocornut_imgui/imgui_impl_sdl.i: resources/ocornut_imgui/imgui_impl_sdl.cc.i

.PHONY : resources/ocornut_imgui/imgui_impl_sdl.i

# target to preprocess a source file
resources/ocornut_imgui/imgui_impl_sdl.cc.i:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_impl_sdl.cc.i
.PHONY : resources/ocornut_imgui/imgui_impl_sdl.cc.i

resources/ocornut_imgui/imgui_impl_sdl.s: resources/ocornut_imgui/imgui_impl_sdl.cc.s

.PHONY : resources/ocornut_imgui/imgui_impl_sdl.s

# target to generate assembly for a file
resources/ocornut_imgui/imgui_impl_sdl.cc.s:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_impl_sdl.cc.s
.PHONY : resources/ocornut_imgui/imgui_impl_sdl.cc.s

resources/ocornut_imgui/imgui_tables.o: resources/ocornut_imgui/imgui_tables.cc.o

.PHONY : resources/ocornut_imgui/imgui_tables.o

# target to build an object file
resources/ocornut_imgui/imgui_tables.cc.o:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_tables.cc.o
.PHONY : resources/ocornut_imgui/imgui_tables.cc.o

resources/ocornut_imgui/imgui_tables.i: resources/ocornut_imgui/imgui_tables.cc.i

.PHONY : resources/ocornut_imgui/imgui_tables.i

# target to preprocess a source file
resources/ocornut_imgui/imgui_tables.cc.i:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_tables.cc.i
.PHONY : resources/ocornut_imgui/imgui_tables.cc.i

resources/ocornut_imgui/imgui_tables.s: resources/ocornut_imgui/imgui_tables.cc.s

.PHONY : resources/ocornut_imgui/imgui_tables.s

# target to generate assembly for a file
resources/ocornut_imgui/imgui_tables.cc.s:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_tables.cc.s
.PHONY : resources/ocornut_imgui/imgui_tables.cc.s

resources/ocornut_imgui/imgui_widgets.o: resources/ocornut_imgui/imgui_widgets.cc.o

.PHONY : resources/ocornut_imgui/imgui_widgets.o

# target to build an object file
resources/ocornut_imgui/imgui_widgets.cc.o:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_widgets.cc.o
.PHONY : resources/ocornut_imgui/imgui_widgets.cc.o

resources/ocornut_imgui/imgui_widgets.i: resources/ocornut_imgui/imgui_widgets.cc.i

.PHONY : resources/ocornut_imgui/imgui_widgets.i

# target to preprocess a source file
resources/ocornut_imgui/imgui_widgets.cc.i:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_widgets.cc.i
.PHONY : resources/ocornut_imgui/imgui_widgets.cc.i

resources/ocornut_imgui/imgui_widgets.s: resources/ocornut_imgui/imgui_widgets.cc.s

.PHONY : resources/ocornut_imgui/imgui_widgets.s

# target to generate assembly for a file
resources/ocornut_imgui/imgui_widgets.cc.s:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/resources/ocornut_imgui/imgui_widgets.cc.s
.PHONY : resources/ocornut_imgui/imgui_widgets.cc.s

resources/perlin/perlin.o: resources/perlin/perlin.cc.o

.PHONY : resources/perlin/perlin.o

# target to build an object file
resources/perlin/perlin.cc.o:
	$(MAKE) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/resources/perlin/perlin.cc.o
.PHONY : resources/perlin/perlin.cc.o

resources/perlin/perlin.i: resources/perlin/perlin.cc.i

.PHONY : resources/perlin/perlin.i

# target to preprocess a source file
resources/perlin/perlin.cc.i:
	$(MAKE) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/resources/perlin/perlin.cc.i
.PHONY : resources/perlin/perlin.cc.i

resources/perlin/perlin.s: resources/perlin/perlin.cc.s

.PHONY : resources/perlin/perlin.s

# target to generate assembly for a file
resources/perlin/perlin.cc.s:
	$(MAKE) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/resources/perlin/perlin.cc.s
.PHONY : resources/perlin/perlin.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... exe"
	@echo "... install/strip"
	@echo "... BigInt"
	@echo "... imgui"
	@echo "... install/local"
	@echo "... FastNoise"
	@echo "... NoiseTool"
	@echo "... Corrade"
	@echo "... CorradeContainers-headers"
	@echo "... CorradeInterconnect"
	@echo "... CorradePluginManager"
	@echo "... CorradePluginManagerObjects"
	@echo "... corrade-rc"
	@echo "... CorradeUtility"
	@echo "... CorradeUtilityObjects"
	@echo "... MagnumFlextGLObjects"
	@echo "... Magnum"
	@echo "... MagnumObjects"
	@echo "... MagnumMathObjects"
	@echo "... MagnumAnimation"
	@echo "... MagnumMath"
	@echo "... MagnumMathAlgorithms"
	@echo "... MagnumPlatform"
	@echo "... MagnumGlxContextObjects"
	@echo "... MagnumSdl2Application"
	@echo "... MagnumPlatformObjects"
	@echo "... MagnumDebugTools"
	@echo "... MagnumDebugToolsObjects"
	@echo "... MagnumGL"
	@echo "... MagnumGLObjects"
	@echo "... MagnumPrimitives"
	@echo "... MagnumSceneGraph"
	@echo "... MagnumSceneGraphObjects"
	@echo "... MagnumShaders"
	@echo "... MagnumShadersObjects"
	@echo "... MagnumShaders_RCS-dependencies"
	@echo "... MagnumShaderTools"
	@echo "... MagnumTrade"
	@echo "... MagnumTradeObjects"
	@echo "... MagnumImGuiIntegration"
	@echo "... resources/VAT/mmccutchen_BigInt/BigInteger.o"
	@echo "... resources/VAT/mmccutchen_BigInt/BigInteger.i"
	@echo "... resources/VAT/mmccutchen_BigInt/BigInteger.s"
	@echo "... resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.o"
	@echo "... resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.i"
	@echo "... resources/VAT/mmccutchen_BigInt/BigIntegerAlgorithms.s"
	@echo "... resources/VAT/mmccutchen_BigInt/BigIntegerUtils.o"
	@echo "... resources/VAT/mmccutchen_BigInt/BigIntegerUtils.i"
	@echo "... resources/VAT/mmccutchen_BigInt/BigIntegerUtils.s"
	@echo "... resources/VAT/mmccutchen_BigInt/BigUnsigned.o"
	@echo "... resources/VAT/mmccutchen_BigInt/BigUnsigned.i"
	@echo "... resources/VAT/mmccutchen_BigInt/BigUnsigned.s"
	@echo "... resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.o"
	@echo "... resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.i"
	@echo "... resources/VAT/mmccutchen_BigInt/BigUnsignedInABase.s"
	@echo "... resources/engine_code/engine.o"
	@echo "... resources/engine_code/engine.i"
	@echo "... resources/engine_code/engine.s"
	@echo "... resources/engine_code/engine_utils.o"
	@echo "... resources/engine_code/engine_utils.i"
	@echo "... resources/engine_code/engine_utils.s"
	@echo "... resources/engine_code/gpu_data.o"
	@echo "... resources/engine_code/gpu_data.i"
	@echo "... resources/engine_code/gpu_data.s"
	@echo "... resources/engine_code/main.o"
	@echo "... resources/engine_code/main.i"
	@echo "... resources/engine_code/main.s"
	@echo "... resources/lodev_lodePNG/lodepng.o"
	@echo "... resources/lodev_lodePNG/lodepng.i"
	@echo "... resources/lodev_lodePNG/lodepng.s"
	@echo "... resources/ocornut_imgui/TextEditor.o"
	@echo "... resources/ocornut_imgui/TextEditor.i"
	@echo "... resources/ocornut_imgui/TextEditor.s"
	@echo "... resources/ocornut_imgui/imgui.o"
	@echo "... resources/ocornut_imgui/imgui.i"
	@echo "... resources/ocornut_imgui/imgui.s"
	@echo "... resources/ocornut_imgui/imgui_demo.o"
	@echo "... resources/ocornut_imgui/imgui_demo.i"
	@echo "... resources/ocornut_imgui/imgui_demo.s"
	@echo "... resources/ocornut_imgui/imgui_draw.o"
	@echo "... resources/ocornut_imgui/imgui_draw.i"
	@echo "... resources/ocornut_imgui/imgui_draw.s"
	@echo "... resources/ocornut_imgui/imgui_gl3w.o"
	@echo "... resources/ocornut_imgui/imgui_gl3w.i"
	@echo "... resources/ocornut_imgui/imgui_gl3w.s"
	@echo "... resources/ocornut_imgui/imgui_impl_opengl3.o"
	@echo "... resources/ocornut_imgui/imgui_impl_opengl3.i"
	@echo "... resources/ocornut_imgui/imgui_impl_opengl3.s"
	@echo "... resources/ocornut_imgui/imgui_impl_sdl.o"
	@echo "... resources/ocornut_imgui/imgui_impl_sdl.i"
	@echo "... resources/ocornut_imgui/imgui_impl_sdl.s"
	@echo "... resources/ocornut_imgui/imgui_tables.o"
	@echo "... resources/ocornut_imgui/imgui_tables.i"
	@echo "... resources/ocornut_imgui/imgui_tables.s"
	@echo "... resources/ocornut_imgui/imgui_widgets.o"
	@echo "... resources/ocornut_imgui/imgui_widgets.i"
	@echo "... resources/ocornut_imgui/imgui_widgets.s"
	@echo "... resources/perlin/perlin.o"
	@echo "... resources/perlin/perlin.i"
	@echo "... resources/perlin/perlin.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

